spring.application.name=routinecare
spring.datasource.url=jdbc:postgresql://localhost:5432/routinecare
spring.datasource.username=postgres
spring.datasource.password=tata1997
spring.jpa.hibernate.ddl-auto=update
